
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int Letra = 27;
  public static final int Fila_Cierre = 11;
  public static final int Parentesis_Cierre = 26;
  public static final int Cuerpo_Apertura = 8;
  public static final int Atributo = 36;
  public static final int Imagen_Apertura = 14;
  public static final int Dato_O_InformacionDesconocida = 42;
  public static final int Dos_Puntos = 40;
  public static final int Enlace = 19;
  public static final int Email = 18;
  public static final int Cuerpo_Cierre = 9;
  public static final int Titulo = 16;
  public static final int Encabezado_Cierre = 5;
  public static final int Imagen_Cierre = 15;
  public static final int Columna = 17;
  public static final int Lista_Apertura = 12;
  public static final int Prueba = 37;
  public static final int Division = 24;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Fila_Apertura = 10;
  public static final int Sim_Cierre = 29;
  public static final int Parentesis_Apertura = 25;
  public static final int Numeros = 32;
  public static final int Imprimir = 39;
  public static final int Tabla_Cierre = 7;
  public static final int Punto_Coma = 30;
  public static final int Link_Enlace = 34;
  public static final int HTML_Cierre = 3;
  public static final int HTML_Apertura = 2;
  public static final int Lista_Cierre = 13;
  public static final int Informacion_O_Identificador = 33;
  public static final int Sim_Apertura = 28;
  public static final int Resta = 22;
  public static final int Negrita = 38;
  public static final int Decimal = 35;
  public static final int Multiplicacion = 23;
  public static final int Suma = 21;
  public static final int Informacion = 41;
  public static final int Encabezado_Apertura = 4;
  public static final int Igual = 20;
  public static final int Tabla_Apertura = 6;
  public static final int Comillas = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HTML_Apertura",
  "HTML_Cierre",
  "Encabezado_Apertura",
  "Encabezado_Cierre",
  "Tabla_Apertura",
  "Tabla_Cierre",
  "Cuerpo_Apertura",
  "Cuerpo_Cierre",
  "Fila_Apertura",
  "Fila_Cierre",
  "Lista_Apertura",
  "Lista_Cierre",
  "Imagen_Apertura",
  "Imagen_Cierre",
  "Titulo",
  "Columna",
  "Email",
  "Enlace",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Parentesis_Apertura",
  "Parentesis_Cierre",
  "Letra",
  "Sim_Apertura",
  "Sim_Cierre",
  "Punto_Coma",
  "Comillas",
  "Numeros",
  "Informacion_O_Identificador",
  "Link_Enlace",
  "Decimal",
  "Atributo",
  "Prueba",
  "Negrita",
  "Imprimir",
  "Dos_Puntos",
  "Informacion",
  "Dato_O_InformacionDesconocida"
  };
}

